openapi: 3.0.0

info:
  title: My Apps
  description: this is a description
  version: 1.0.0-beta
  
tags:
  - name: Users
  - name: Places


paths:
  '/users/login':
    post:
      summary: this is a login endpoint
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                 type: number
                 example: 1
                username:
                  type: string
                  example: bambang
                email:
                   type: string 
                   example: ekatejo1111@gmail.com
                password:
                  type: string
                  example: supersecretpassword
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  id:
                    type: number
                    example: 1
                  username:
                    type: string
                    example: bambang
                  email:
                   type: string 
                   example: ekatejo1111@gmail.com
                  token:
                    type: string
                    example: kjasldkjalksdjalkjdlaksjdkalj
        '402':
          description: user failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: bad request, user failure
                  rescode:
                    type: number
                    example: 402
  '/api/getuser/{id}':
    get:
      summary: this is a get profile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags:
        - Users
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema: 
                type: object
                properties:
                    message:
                     type: string
                     example: success
                    id:
                     type: number
                     example: 1
                    username:
                     type: string
                     example: bambang
                    email:
                     type: string 
                     example: ekatejo1111@gmail.com
        '402':
          $ref: "#/components/responses/402badrequest"
  '/delete/User/{id}':
    delete:
      summary: this is a delete profile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags:
        - Users
      responses:
        '200':
          description: Success delete
          content:
            application/json:
              schema:
                  allOf:
                    - $ref: "#/components/schemas/success200"
        '402':
          description: user failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: bad request, user failure
                  rescode:
                    type: number
                    example: 402
  '/put/users/{id}':
    put:
      summary: this is a login endpoint
      parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                 type: number
                 example: 1
                username:
                  type: string
                  example: bambang
                email:
                   type: string 
                   example: ekatejo1111@gmail.com
                password:
                  type: string
                  example: supersecretpassword
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  id:
                    type: number
                    example: 1
                  username:
                    type: string
                    example: bambang
                  email:
                   type: string 
                   example: ekatejo1111@gmail.com
                  token:
                    type: string
                    example: kjasldkjalksdjalkjdlaksjdkalj
        '402':
          description: user failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: bad request, user failure
                  rescode:
                    type: number
                    example: 402
  '/places':
    post:
      summary: this is a login endpoint
      tags:
        - Places
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                 type: number
                 example: 1
                author_id:
                  type: number
                  example: 1
                name:
                  type: string
                  example: pantai selatan
                location:
                   type: string 
                   example: bengkulu
                description:
                  type: string
                  example: ini tempat wisata
                rating:  
                   type: number
                   example: 9
      responses:
        '200':
          description: success response
          content:
            application/json:
             schema:
              type: object
              properties:
                id:
                 type: number
                 example: 1
                author_id:
                  type: number
                  example: 1
                name:
                  type: string
                  example: pantai selatan
                location:
                   type: string 
                   example: bengkulu
                description:
                  type: string
                  example: ini tempat wisata
                rating:  
                   type: number
                   example: 9
        '402':
          description: user failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: bad request, user failure
                  rescode:
                    type: number
                    example: 402
  '/Places{id}':
    get:
      summary: this is a get profile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags:
        - Places
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema: 
                type: object
                properties:
                    message:
                     type: string
                     example: success
                    id:
                     type: number
                     example: 1
                    author_id:
                     type: number
                     example: 1
                    name:
                     type: string 
                     example: pantai selatan
                    location:
                     type: string
                     example: bengkulu
                    description:
                     type: string
                     example: ini tempat wisata
                    rating: 
                     type: number
                     example: 9
        '402':
          $ref: "#/components/responses/402badrequest"  
  '/delete/Places/{id}':
    delete:
      summary: this is a delete profile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags:
        - Places
      responses:
        '200':
          description: Success delete
          content:
            application/json:
              schema:
                  allOf:
                    - $ref: "#/components/schemas/success200"
        '402':
          description: user failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: bad request, user failure
                  rescode:
                    type: number
                    example: 402
components:
  schemas:
    success200:
      type: object
      properties:
         message:
           type: string
           example: success
         rescode:
           type: number
           example: 200
  responses:
    402badrequest:
      description: user failure
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: bad request, user failure
              rescode:
                type: number
                example: 402
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT